version: '3.8'
services:
  postgres:
    build:
      context: services/postgres
      dockerfile: Dockerfile.development
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=docker
      - POSTGRES_PASSWORD=Vorobei55
    volumes:
      - "db-data:/var/lib/postgresql/data"


  app:
    build:
      context: services/app
      dockerfile: Dockerfile.development
    environment:
      - PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/vv
      - JS_URL=http://localhost:8085
    image: 'my-java-app'
    ports:
      - 8081:8081
    depends_on:
      - postgres
  js:
    build:
      context: services/js
      dockerfile: Dockerfile.development
    image: 'my-js-app'
    ports:
      - 80:80

volumes:
  db-data: