version: '3.8'
services:
  postgres:
    build:
      context: services/postgres
      dockerfile: Dockerfile.development
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=testdb
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - "db-data:/var/lib/postgresql/data"

  app:
    build:
      context: services/app
      dockerfile: Dockerfile.development
    environment:
     SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/testdb
    image: 'my-java-app'
    ports:
      - 8081:8081
    depends_on:
      - postgres
  js:
    build:
      context: services/js
      dockerfile: Dockerfile.development
    image: 'my-js-app'
    ports:
      - 80:80

volumes:
  db-data:

#version: '3.8'
#services:
#   postgres:
#    build:
#      context: services/postgres
#      dockerfile: Dockerfile.development
#    ports:
#      - "5433:5432"
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_DB=test
#      - POSTGRES_PASSWORD=admin
#    volumes:
#      - "db-data:/var/lib/postgresql/data"

#   app:
#    build:
#      context: services/app
#      dockerfile: Dockerfile.development
#      environment:
#        - PORT=8081
#        - SPRING_DATASOURCE_URL=jdbc:postgresql://test
#      image: 'diploma'
#      ports:
#        - 8081:8081
#      depends_on:
#        - postgres
#  js:
#    build:
#      context: services/js
#      dockerfile: Dockerfile.development
#    image: 'my-js-app'
#    ports:
#      - 80:80
#
#  volumes:
#    db-data:
#version: "3"

#  app:
#    build:
#    container_name: springapp
#    ports:
#      - 8000:8080
#    restart: always
#    depends_on:
#      - postgres
#  postgres:
#    image: postgres
#    container_name: db
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=testdb
#      - PGDATA=/var/lib/postgresql/data/pgdata
#    ports:
#      - 5000:5432
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#    restart: always
#volumes:
#  pgdata:
#  js:
#    build:
#      context: services/js
#      dockerfile: Dockerfile.development
#    image: 'my-js-app'
#    ports:
#      - 80:80
#
#  volumes:
#    db-data: